[grpc.test]
debug = true # 开启后并加上export EGO_DEBUG=true，可以看到每次grpc请求，配置名、地址、耗时、请求数据、响应数据
addr = "etcd:///main"
#balancerName = "round_robin" # 默认值
#dialTimeout = "1s" # 默认值
#enableAccessInterceptor = true
#enableAccessInterceptorRes = true
#enableAccessInterceptorReq = true

[etcd]
addrs=["127.0.0.1:2379"]
connectTimeout = "1s"
secure = false

[registry]
scheme = "etcd" # grpc resolver默认scheme为"etcd"，你可以自行修改