[dm.test]
dialect = "dm"
debug = true # ego重写gorm debug，打开后可以看到，配置名、地址、耗时、请求数据、响应数据
#   rawDebug = true 原生gorm debug
dsn = "sysdba:shimo2021@192.168.242.136:5236/SYSDBA"
onFail = "panic" # 失败后，直接fail fast，panic操作
#   connMaxLifetime = "300s"
#   maxIdleConns = 50
#   maxOpenConns = 100
#   disableTrace = false
#   disableMetric = false
#   enableDetailSQL = false
#   enableAccessInterceptor = true
#   enableAccessInterceptorReq = true
#   enableAccessInterceptorRes = true
